# Site settings
title: Yellow Wing Roasters
email: hello@yellowwingroasters.com
description: >-
  Small-batch coffee roasting.
baseurl: ""
url: "https://yellowwingroasters.com"

# Theme
remote_theme: sblisesivdin/biscuit

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

# Collections
collections:
  roasts:
    output: true
    permalink: /roasts/:path/

# Default layouts per collection
defaults:
  - scope:
      path: ""
    values:
      image: /images/social-preview.jpg
  - scope:
      path: ""
      type: roasts
    values:
      layout: roast

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
