# Site settings
title: Yellow Wing Roasters
email: chirp@yellowwingroasters.com
description: >-
  Small-batch coffee roasting.
baseurl: ""
url: "https://yellowwingroasters.com"
subscription_api_url: "https://script.google.com/macros/s/AKfycbwLndIoyAjX12dU4wccUsIg-4QiIRIawziVn2POikVQN7PFgXymlA-GcaQHD0rqeN65/exec"


# Theme
remote_theme: sblisesivdin/biscuit

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

# Collections
collections:
  roasts:
    output: true
    permalink: /roasts/:path/

# Default layouts per collection
defaults:
  - scope:
      path: ""
    values:
      image: /images/social-preview-v2.png
  - scope:
      path: ""
      type: roasts
    values:
      layout: roast

category_order:
  - blend
  - seasonal
  - single origin
  - subscriptions
  - flight

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  # - preview-bags.html
